export { default as Daedalus } from './png/daedaluslogo-cover.png'
export { default as Hero } from './png/daedalushero.png'
export { default as Radial } from './png/radial.png'
export { default as Man } from './png/man.png'
export { default as Cube } from './png/cube.png'
export { default as Avatar } from './jpg/daedalus-logo.jpg'
